//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace windows_client.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("windows_client.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string AppBar_Next_Btn {
            get {
                return ResourceManager.GetString("AppBar_Next_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity issue..
        /// </summary>
        public static string Connectivity_Issue {
            get {
                return ResourceManager.GetString("Connectivity_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string EnterName_Done_AppBarBtnTxt {
            get {
                return ResourceManager.GetString("EnterName_Done_AppBarBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting you in.
        /// </summary>
        public static string EnterName_Msg_TxtBlk {
            get {
                return ResourceManager.GetString("EnterName_Msg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EnterName_Name_Hint {
            get {
                return ResourceManager.GetString("EnterName_Name_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name below :.
        /// </summary>
        public static string EnterName_Name_TxtBlk {
            get {
                return ResourceManager.GetString("EnterName_Name_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!! Name not set. Try Again!!.
        /// </summary>
        public static string EnterName_NameErrorTxt {
            get {
                return ResourceManager.GetString("EnterName_NameErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Contacts ....
        /// </summary>
        public static string EnterName_ScanningContacts_Txt {
            get {
                return ResourceManager.GetString("EnterName_ScanningContacts_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re all set on .
        /// </summary>
        public static string EnterName_YourMsisdn_TxtBlk {
            get {
                return ResourceManager.GetString("EnterName_YourMsisdn_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number below to get started :.
        /// </summary>
        public static string EnterNumber_EnterNum_TxtBlk {
            get {
                return ResourceManager.GetString("EnterNumber_EnterNum_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect phone number..
        /// </summary>
        public static string EnterNumber_IncorrectPh_TxtBlk {
            get {
                return ResourceManager.GetString("EnterNumber_IncorrectPh_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Phone Number.
        /// </summary>
        public static string EnterNumber_MsgBoxHeader_Msg {
            get {
                return ResourceManager.GetString("EnterNumber_MsgBoxHeader_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid phone number..
        /// </summary>
        public static string EnterNumber_MsgBoxText_Msg {
            get {
                return ResourceManager.GetString("EnterNumber_MsgBoxText_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string EnterNumber_Ph_Hint_TxtBox {
            get {
                return ResourceManager.GetString("EnterNumber_Ph_Hint_TxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNTRY.
        /// </summary>
        public static string EnterNumber_SelectCountry_TxtBlk {
            get {
                return ResourceManager.GetString("EnterNumber_SelectCountry_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying your number..
        /// </summary>
        public static string EnterNumber_VerifyNumberMsg_TxtBlk {
            get {
                return ResourceManager.GetString("EnterNumber_VerifyNumberMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t call you. Try again later..
        /// </summary>
        public static string EnterPin_CallErrorMsg_MsgBox {
            get {
                return ResourceManager.GetString("EnterPin_CallErrorMsg_MsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling you for PIN..
        /// </summary>
        public static string EnterPin_CallingMsg_MsgBox {
            get {
                return ResourceManager.GetString("EnterPin_CallingMsg_MsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call me for PIN.
        /// </summary>
        public static string EnterPin_CallMe_Btn {
            get {
                return ResourceManager.GetString("EnterPin_CallMe_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN not valid. Please try again..
        /// </summary>
        public static string EnterPin_PinError_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_PinError_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string EnterPin_PinHint {
            get {
                return ResourceManager.GetString("EnterPin_PinHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Did you get an SMS pin? Enter it below :.
        /// </summary>
        public static string EnterPin_PinMsg_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_PinMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive an SMS?.
        /// </summary>
        public static string EnterPin_SMSError_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_SMSError_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap Here.
        /// </summary>
        public static string EnterPin_Taphere_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_Taphere_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered a wrong number?.
        /// </summary>
        public static string EnterPin_WrongNumMsg_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_WrongNumMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error. Try Again!!.
        /// </summary>
        public static string NetworkError_TryAgain {
            get {
                return ResourceManager.GetString("NetworkError_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Free SMS can only be sent to India.
        /// </summary>
        public static string Walkthrough_FreeMsgToIndia_Txt {
            get {
                return ResourceManager.GetString("Walkthrough_FreeMsgToIndia_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For every friend who joins, you get 50 Free hike SMS every month.
        /// </summary>
        public static string Walkthrough_FreeSmsReward_Txt {
            get {
                return ResourceManager.GetString("Walkthrough_FreeSmsReward_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Friends Earn Rewards..
        /// </summary>
        public static string Walkthrough_InviteFriends_Txt {
            get {
                return ResourceManager.GetString("Walkthrough_InviteFriends_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free, always, worldwide.
        /// </summary>
        public static string Walkthrough_TitleMsg_1 {
            get {
                return ResourceManager.GetString("Walkthrough_TitleMsg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also message friends not on hike for free with Free hike SMS.
        /// </summary>
        public static string Walkthrough_TitleMsg_2 {
            get {
                return ResourceManager.GetString("Walkthrough_TitleMsg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap next to confirm that you are 13+ years of age.
        /// </summary>
        public static string WelcomePage_13YrsMsg_TxtBlk {
            get {
                return ResourceManager.GetString("WelcomePage_13YrsMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string WelcomePage_Accept_AppBar {
            get {
                return ResourceManager.GetString("WelcomePage_Accept_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun, free messaging for life.
        /// </summary>
        public static string WelcomePage_HikeMsg_TxtBlk {
            get {
                return ResourceManager.GetString("WelcomePage_HikeMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notifications are turned on by default.
        /// </summary>
        public static string WelcomePage_PushMsg_TxtBlk {
            get {
                return ResourceManager.GetString("WelcomePage_PushMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Privacy.
        /// </summary>
        public static string WelcomePage_TnP_HlBtn {
            get {
                return ResourceManager.GetString("WelcomePage_TnP_HlBtn", resourceCulture);
            }
        }
    }
}
