//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace windows_client.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("windows_client.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string AppBar_Done_Btn {
            get {
                return ResourceManager.GetString("AppBar_Done_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string AppBar_Next_Btn {
            get {
                return ResourceManager.GetString("AppBar_Next_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change Profile Image. Try Later!!.
        /// </summary>
        public static string Cannot_Change_Img_Error_Txt {
            get {
                return ResourceManager.GetString("Cannot_Change_Img_Error_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot select photo while phone is connected to computer..
        /// </summary>
        public static string Cannot_Select_Pic_Phone_Connected_to_PC {
            get {
                return ResourceManager.GetString("Cannot_Select_Pic_Phone_Connected_to_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity issue..
        /// </summary>
        public static string Connectivity_Issue {
            get {
                return ResourceManager.GetString("Connectivity_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  added you as favourite. Would you like to do the same?.
        /// </summary>
        public static string Conversations_AddedYouToFav_Txt {
            get {
                return ResourceManager.GetString("Conversations_AddedYouToFav_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Favourites.
        /// </summary>
        public static string Conversations_ContextMenu_RemoveFromFav_Txt {
            get {
                return ResourceManager.GetString("Conversations_ContextMenu_RemoveFromFav_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Chats.
        /// </summary>
        public static string Conversations_DelAllChats_Txt {
            get {
                return ResourceManager.GetString("Conversations_DelAllChats_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Chat.
        /// </summary>
        public static string Conversations_DelChat_Txt {
            get {
                return ResourceManager.GetString("Conversations_DelChat_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure about deleting this chat?.
        /// </summary>
        public static string Conversations_Delete_Chat_Confirmation {
            get {
                return ResourceManager.GetString("Conversations_Delete_Chat_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure about deleting all chats?.
        /// </summary>
        public static string Conversations_Delete_Chats_Confirmation {
            get {
                return ResourceManager.GetString("Conversations_Delete_Chats_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string Conversations_EditProfile_Txt {
            get {
                return ResourceManager.GetString("Conversations_EditProfile_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free SMS.
        /// </summary>
        public static string Conversations_FreeSms_Txt {
            get {
                return ResourceManager.GetString("Conversations_FreeSms_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hike Contacts.
        /// </summary>
        public static string Conversations_HikeContacts_Btn {
            get {
                return ResourceManager.GetString("Conversations_HikeContacts_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new chat.
        /// </summary>
        public static string Conversations_NewChat_AppBar_Btn {
            get {
                return ResourceManager.GetString("Conversations_NewChat_AppBar_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is on hike..
        /// </summary>
        public static string Conversations_OnHike_Txt {
            get {
                return ResourceManager.GetString("Conversations_OnHike_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send {0} free sms..
        /// </summary>
        public static string Conversations_OnSMS_Txt {
            get {
                return ResourceManager.GetString("Conversations_OnSMS_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string Conversations_Pending_NotNow_Btn {
            get {
                return ResourceManager.GetString("Conversations_Pending_NotNow_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Conversations_Pending_Yes_Btn {
            get {
                return ResourceManager.GetString("Conversations_Pending_Yes_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chats.
        /// </summary>
        public static string Conversations_Pivot_Chats_Header_Txt {
            get {
                return ResourceManager.GetString("Conversations_Pivot_Chats_Header_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favourites.
        /// </summary>
        public static string Conversations_Pivot_Favourites_Header_Txt {
            get {
                return ResourceManager.GetString("Conversations_Pivot_Favourites_Header_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Conversations_Pivot_Profile_Header_Txt {
            get {
                return ResourceManager.GetString("Conversations_Pivot_Profile_Header_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Name.
        /// </summary>
        public static string Conversations_ProfileName_Default_Txt {
            get {
                return ResourceManager.GetString("Conversations_ProfileName_Default_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure about removing this contact from favourites?.
        /// </summary>
        public static string Conversations_RemFromFav_Confirm_Txt {
            get {
                return ResourceManager.GetString("Conversations_RemFromFav_Confirm_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favourites.
        /// </summary>
        public static string Conversations_RemFromFav_Txt {
            get {
                return ResourceManager.GetString("Conversations_RemFromFav_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on &apos;+&apos; next to a friend to add them as a favourite.
        /// </summary>
        public static string Conversations_TapYesToAdd_Txt {
            get {
                return ResourceManager.GetString("Conversations_TapYesToAdd_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell a friend.
        /// </summary>
        public static string Conversations_TellFriend_Txt {
            get {
                return ResourceManager.GetString("Conversations_TellFriend_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your favourites.
        /// </summary>
        public static string Conversations_YourFav_Txt {
            get {
                return ResourceManager.GetString("Conversations_YourFav_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Txt {
            get {
                return ResourceManager.GetString("Delete_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EditProfile_Email_TxtBlk {
            get {
                return ResourceManager.GetString("EditProfile_Email_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string EditProfile_FullName_TxtBlk {
            get {
                return ResourceManager.GetString("EditProfile_FullName_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string EditProfile_Gender_TxtBlk {
            get {
                return ResourceManager.GetString("EditProfile_Gender_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string EditProfile_GenderFemale_lstPckr {
            get {
                return ResourceManager.GetString("EditProfile_GenderFemale_lstPckr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string EditProfile_GenderMale_LstPckr {
            get {
                return ResourceManager.GetString("EditProfile_GenderMale_LstPckr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string EditProfile_GenderSelect_LstPckr {
            get {
                return ResourceManager.GetString("EditProfile_GenderSelect_LstPckr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string EditProfile_Phone_TxtBlk {
            get {
                return ResourceManager.GetString("EditProfile_Phone_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string EditProfile_Save_AppBarBtnTxt {
            get {
                return ResourceManager.GetString("EditProfile_Save_AppBarBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile_Title_TxtBlk {
            get {
                return ResourceManager.GetString("EditProfile_Title_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting you in.
        /// </summary>
        public static string EnterName_Msg_TxtBlk {
            get {
                return ResourceManager.GetString("EnterName_Msg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EnterName_Name_Hint {
            get {
                return ResourceManager.GetString("EnterName_Name_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name below :.
        /// </summary>
        public static string EnterName_Name_TxtBlk {
            get {
                return ResourceManager.GetString("EnterName_Name_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!! Name not set. Try Again!!.
        /// </summary>
        public static string EnterName_NameErrorTxt {
            get {
                return ResourceManager.GetString("EnterName_NameErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Contacts ....
        /// </summary>
        public static string EnterName_ScanningContacts_Txt {
            get {
                return ResourceManager.GetString("EnterName_ScanningContacts_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re all set on .
        /// </summary>
        public static string EnterName_YourMsisdn_TxtBlk {
            get {
                return ResourceManager.GetString("EnterName_YourMsisdn_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number below to get started :.
        /// </summary>
        public static string EnterNumber_EnterNum_TxtBlk {
            get {
                return ResourceManager.GetString("EnterNumber_EnterNum_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect phone number..
        /// </summary>
        public static string EnterNumber_IncorrectPh_TxtBlk {
            get {
                return ResourceManager.GetString("EnterNumber_IncorrectPh_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Phone Number.
        /// </summary>
        public static string EnterNumber_MsgBoxHeader_Msg {
            get {
                return ResourceManager.GetString("EnterNumber_MsgBoxHeader_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid phone number..
        /// </summary>
        public static string EnterNumber_MsgBoxText_Msg {
            get {
                return ResourceManager.GetString("EnterNumber_MsgBoxText_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string EnterNumber_Ph_Hint_TxtBox {
            get {
                return ResourceManager.GetString("EnterNumber_Ph_Hint_TxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNTRY.
        /// </summary>
        public static string EnterNumber_SelectCountry_TxtBlk {
            get {
                return ResourceManager.GetString("EnterNumber_SelectCountry_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying your number..
        /// </summary>
        public static string EnterNumber_VerifyNumberMsg_TxtBlk {
            get {
                return ResourceManager.GetString("EnterNumber_VerifyNumberMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t call you. Try again later..
        /// </summary>
        public static string EnterPin_CallErrorMsg_MsgBox {
            get {
                return ResourceManager.GetString("EnterPin_CallErrorMsg_MsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling you for PIN..
        /// </summary>
        public static string EnterPin_CallingMsg_MsgBox {
            get {
                return ResourceManager.GetString("EnterPin_CallingMsg_MsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call me for PIN.
        /// </summary>
        public static string EnterPin_CallMe_Btn {
            get {
                return ResourceManager.GetString("EnterPin_CallMe_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN not valid. Please try again..
        /// </summary>
        public static string EnterPin_PinError_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_PinError_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string EnterPin_PinHint {
            get {
                return ResourceManager.GetString("EnterPin_PinHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Did you get an SMS pin? Enter it below :.
        /// </summary>
        public static string EnterPin_PinMsg_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_PinMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive an SMS?.
        /// </summary>
        public static string EnterPin_SMSError_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_SMSError_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap Here.
        /// </summary>
        public static string EnterPin_Taphere_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_Taphere_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered a wrong number?.
        /// </summary>
        public static string EnterPin_WrongNumMsg_TxtBlk {
            get {
                return ResourceManager.GetString("EnterPin_WrongNumMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect and get a.
        /// </summary>
        public static string FreeSMS_Cnnct_TxtBlk1 {
            get {
                return ResourceManager.GetString("FreeSMS_Cnnct_TxtBlk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 Free SMS.
        /// </summary>
        public static string FreeSMS_Cnnct_TxtBlk2 {
            get {
                return ResourceManager.GetString("FreeSMS_Cnnct_TxtBlk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instantly.
        /// </summary>
        public static string FreeSMS_Cnnct_TxtBlk3 {
            get {
                return ResourceManager.GetString("FreeSMS_Cnnct_TxtBlk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn an extra.
        /// </summary>
        public static string FreeSMS_EarnFreeSMS_TxtBlk1 {
            get {
                return ResourceManager.GetString("FreeSMS_EarnFreeSMS_TxtBlk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 free SMS.
        /// </summary>
        public static string FreeSMS_EarnFreeSMS_TxtBlk2 {
            get {
                return ResourceManager.GetString("FreeSMS_EarnFreeSMS_TxtBlk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per month for every friend that joins through you..
        /// </summary>
        public static string FreeSMS_EarnFreeSMS_TxtBlk3 {
            get {
                return ResourceManager.GetString("FreeSMS_EarnFreeSMS_TxtBlk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string FreeSMS_fbConnStatus_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_fbConnStatus_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string FreeSMS_fbOrTwitter_Connected {
            get {
                return ResourceManager.GetString("FreeSMS_fbOrTwitter_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Post.
        /// </summary>
        public static string FreeSMS_FbPost_MsgBxCaption {
            get {
                return ResourceManager.GetString("FreeSMS_FbPost_MsgBxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully posted to facebook..
        /// </summary>
        public static string FreeSMS_FbPostSuccess_MsgBx {
            get {
                return ResourceManager.GetString("FreeSMS_FbPostSuccess_MsgBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FreeSMS_FbPostSuccess_MsgBxCaptn {
            get {
                return ResourceManager.GetString("FreeSMS_FbPostSuccess_MsgBxCaptn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hike to hike.
        /// </summary>
        public static string FreeSMS_H2HHeader_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_H2HHeader_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Worldwide.
        /// </summary>
        public static string FreeSMS_H2HText_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_H2HText_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hike to SMS.
        /// </summary>
        public static string FreeSMS_H2SHeader_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_H2SHeader_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your free SMS refill on the 1st of every month.
        /// </summary>
        public static string FreeSMS_H2SText_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_H2SText_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Free SMS can only be sent to India at the moment.
        /// </summary>
        public static string FreeSMS_IndiaOnly_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_IndiaOnly_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Now.
        /// </summary>
        public static string FreeSMS_InviteNow_Btn {
            get {
                return ResourceManager.GetString("FreeSMS_InviteNow_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite via SMS.
        /// </summary>
        public static string FreeSMS_InviteSMS_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_InviteSMS_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free SMS.
        /// </summary>
        public static string FreeSMS_Title_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_Title_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string FreeSMS_twConnStatus_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_twConnStatus_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Post.
        /// </summary>
        public static string FreeSMS_TwPost_MsgBxCaption {
            get {
                return ResourceManager.GetString("FreeSMS_TwPost_MsgBxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully posted to twitter..
        /// </summary>
        public static string FreeSMS_TwPostSuccess_MsgBx {
            get {
                return ResourceManager.GetString("FreeSMS_TwPostSuccess_MsgBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        public static string FreeSMS_unlimitedTxtBlck_TxtBlk {
            get {
                return ResourceManager.GetString("FreeSMS_unlimitedTxtBlck_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink Facebook.
        /// </summary>
        public static string FreeSMS_UnlinkFacebook_MsgBxCaptn {
            get {
                return ResourceManager.GetString("FreeSMS_UnlinkFacebook_MsgBxCaptn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unlink your account?.
        /// </summary>
        public static string FreeSMS_UnlinkFbOrTwConfirm_MsgBx {
            get {
                return ResourceManager.GetString("FreeSMS_UnlinkFbOrTwConfirm_MsgBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Unlinked Account..
        /// </summary>
        public static string FreeSMS_UnlinkFbOrTwSuccess_MsgBx {
            get {
                return ResourceManager.GetString("FreeSMS_UnlinkFbOrTwSuccess_MsgBx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink Twitter.
        /// </summary>
        public static string FreeSMS_UnlinkTwitter_MsgBxCaptn {
            get {
                return ResourceManager.GetString("FreeSMS_UnlinkTwitter_MsgBxCaptn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Logout.
        /// </summary>
        public static string FreeSMS_UnlinkTwSuccess_MsgBxCaptn {
            get {
                return ResourceManager.GetString("FreeSMS_UnlinkTwSuccess_MsgBxCaptn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Chat.
        /// </summary>
        public static string GrpChat_Txt {
            get {
                return ResourceManager.GetString("GrpChat_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore_Txt {
            get {
                return ResourceManager.GetString("Ignore_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error. Try Again!!.
        /// </summary>
        public static string NetworkError_TryAgain {
            get {
                return ResourceManager.GetString("NetworkError_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connectivity.
        /// </summary>
        public static string No_Network_Txt {
            get {
                return ResourceManager.GetString("No_Network_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        public static string Please_Try_Again_Txt {
            get {
                return ResourceManager.GetString("Please_Try_Again_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already added !!.
        /// </summary>
        public static string SelectUser_AlreadyAdded_Txt {
            get {
                return ResourceManager.GetString("SelectUser_AlreadyAdded_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add user !!.
        /// </summary>
        public static string SelectUser_CantAddUser_Txt {
            get {
                return ResourceManager.GetString("SelectUser_CantAddUser_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[{1}] will be removed from group..
        /// </summary>
        public static string SelectUser_ContactRemoved_Txt {
            get {
                return ResourceManager.GetString("SelectUser_ContactRemoved_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Number.
        /// </summary>
        public static string SelectUser_EnterValidNo_Txt {
            get {
                return ResourceManager.GetString("SelectUser_EnterValidNo_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT.
        /// </summary>
        public static string SelectUser_Header_Txt {
            get {
                return ResourceManager.GetString("SelectUser_Header_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} users already selected.
        /// </summary>
        public static string SelectUser_MaxUsersSelected_Txt {
            get {
                return ResourceManager.GetString("SelectUser_MaxUsersSelected_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Contacts.
        /// </summary>
        public static string SelectUser_RefreshContacts_Txt {
            get {
                return ResourceManager.GetString("SelectUser_RefreshContacts_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a minute or two....
        /// </summary>
        public static string SelectUser_RefreshWaitMsg_Txt {
            get {
                return ResourceManager.GetString("SelectUser_RefreshWaitMsg_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Contact?.
        /// </summary>
        public static string SelectUser_RemoveContact_Txt {
            get {
                return ResourceManager.GetString("SelectUser_RemoveContact_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here to message this person.
        /// </summary>
        public static string SelectUser_TapMsg_Txt {
            get {
                return ResourceManager.GetString("SelectUser_TapMsg_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        public static string SelectUser_Title_Txt {
            get {
                return ResourceManager.GetString("SelectUser_Title_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Search or Enter Phone Number....
        /// </summary>
        public static string SelectUser_TxtBoxHint_Txt {
            get {
                return ResourceManager.GetString("SelectUser_TxtBoxHint_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already added to group..
        /// </summary>
        public static string SelectUser_UserAlreadyAdded_Txt {
            get {
                return ResourceManager.GetString("SelectUser_UserAlreadyAdded_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Left.
        /// </summary>
        public static string SMS_Left_Txt {
            get {
                return ResourceManager.GetString("SMS_Left_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something went wrong!.
        /// </summary>
        public static string Something_Wrong_Txt {
            get {
                return ResourceManager.GetString("Something_Wrong_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update_Txt {
            get {
                return ResourceManager.GetString("Update_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Free SMS can only be sent to India.
        /// </summary>
        public static string Walkthrough_FreeMsgToIndia_Txt {
            get {
                return ResourceManager.GetString("Walkthrough_FreeMsgToIndia_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For every friend who joins, you get 50 Free hike SMS every month.
        /// </summary>
        public static string Walkthrough_FreeSmsReward_Txt {
            get {
                return ResourceManager.GetString("Walkthrough_FreeSmsReward_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Friends Earn Rewards..
        /// </summary>
        public static string Walkthrough_InviteFriends_Txt {
            get {
                return ResourceManager.GetString("Walkthrough_InviteFriends_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let&apos;s hike.
        /// </summary>
        public static string Walkthrough_LetsHike_Txt {
            get {
                return ResourceManager.GetString("Walkthrough_LetsHike_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free, always, worldwide.
        /// </summary>
        public static string Walkthrough_TitleMsg_1 {
            get {
                return ResourceManager.GetString("Walkthrough_TitleMsg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also message friends not on hike for free with Free hike SMS.
        /// </summary>
        public static string Walkthrough_TitleMsg_2 {
            get {
                return ResourceManager.GetString("Walkthrough_TitleMsg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap next to confirm that you are 13+ years of age.
        /// </summary>
        public static string WelcomePage_13YrsMsg_TxtBlk {
            get {
                return ResourceManager.GetString("WelcomePage_13YrsMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accept.
        /// </summary>
        public static string WelcomePage_Accept_AppBar {
            get {
                return ResourceManager.GetString("WelcomePage_Accept_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun, free messaging for life.
        /// </summary>
        public static string WelcomePage_HikeMsg_TxtBlk {
            get {
                return ResourceManager.GetString("WelcomePage_HikeMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notifications are turned on by default.
        /// </summary>
        public static string WelcomePage_PushMsg_TxtBlk {
            get {
                return ResourceManager.GetString("WelcomePage_PushMsg_TxtBlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Privacy.
        /// </summary>
        public static string WelcomePage_TnP_HlBtn {
            get {
                return ResourceManager.GetString("WelcomePage_TnP_HlBtn", resourceCulture);
            }
        }
    }
}
